include:
  - ./mosquitto/docker-compose.yaml

services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: npm run start
    depends_on:
      - mosquitto
    restart: unless-stopped
